//null = <To Be Implemented> or <Not usable> 

const effectTypes = {
    "BARRIER"           :"Barrier",
    "BLOCK_CRACK"       :"null", 	 
    "BLOCK_DUST"        :"null", 	 
    "CLOUD"             :"Cloud",
    "CRIT" 	            :"Critical Hit",
    "CRIT_MAGIC"        :"Magical Critical Hit", 
    "DAMAGE_INDICATOR"  :"Damage Initcator",
    "DRAGON_BREATH"     :"Dragonbreath",
    "DRIP_LAVA"         :"null", 	 
    "DRIP_WATER" 	    :"null",
    "ENCHANTMENT_TABLE" :"Runes",
    "END_ROD"           :"null", 	 
    "EXPLOSION_HUGE" 	:"null",
    "EXPLOSION_LARGE" 	:"null",
    "EXPLOSION_NORMAL" 	:"null",
    "FALLING_DUST"      :"null", 
    "FIREWORKS_SPARK"   :"null", 	 
    "FLAME"             :"Flames",	 
    "FOOTSTEP" 	        :"Footstep",
    "HEART"             :"Hearts", 
    "ITEM_CRACK"        :"null", 	 
    "ITEM_TAKE"         :"null", 	 
    "LAVA"              :"null", 	 
    "MOB_APPEARANCE"    :"null", 	 
    "NOTE"              :"Notes", 	 
    "PORTAL"            :"null", 	 
    "REDSTONE"          :"Colored Particle", 	 
    "SLIME"             :"null", 	 
    "SMOKE_LARGE"       :"null", 	 
    "SMOKE_NORMAL"      :"null", 	 
    "SNOW_SHOVEL"       :"null", 	 
    "SNOWBALL"          :"null", 	 
    "SPELL"             :"Spell", 	 
    "SPELL_INSTANT"     :"null",
    "SPELL_MOB" 	    :"null",
    "SPELL_MOB_AMBIENT" :"null",
    "SPELL_WITCH" 	    :"null",
    "SPIT" 	            :"null",
    "SUSPENDED" 	    :"null", 
    "SUSPENDED_DEPTH" 	:"null",
    "SWEEP_ATTACK" 	    :"null",
    "TOTEM" 	        :"null",
    "TOWN_AURA" 	    :"null",
    "VILLAGER_ANGRY" 	:"null", 
    "VILLAGER_HAPPY" 	:"null", 
    "WATER_BUBBLE" 	    :"null",
    "WATER_DROP" 	    :"null",
    "WATER_SPLASH" 	    :"Water Splash",
    "WATER_WAKE"        :"null",
}

module.exports = effectTypes;